import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Sparkles, Upload, Plus, Trash2, Save } from 'lucide-react';
import api from '../services/api';
import './CreateInvoice.css';

interface InvoiceItem {
  service_name: string;
  description: string;
  amount: number;
}

const CreateInvoice = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);
  
  const [formData, setFormData] = useState({
    client_name: '',
    client_email: '',
    client_phone: '',
    billing_address: '',
    shipping_address: '',
    client_tax_number: '',
    invoice_number: '',
    issue_date: new Date().toISOString().split('T')[0],
    due_date: new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
    discount: 0,
  });

  const [items, setItems] = useState<InvoiceItem[]>([
    { service_name: '', description: '', amount: 0 }
  ]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleItemChange = (index: number, field: string, value: string | number) => {
    const newItems = [...items];
    newItems[index] = { ...newItems[index], [field]: value };
    setItems(newItems);
  };

  const addItem = () => {
    setItems([...items, { service_name: '', description: '', amount: 0 }]);
  };

  const removeItem = (index: number) => {
    if (items.length > 1) {
      setItems(items.filter((_, i) => i !== index));
    }
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files || e.target.files.length === 0) return;
    const file = e.target.files[0];
    
    setAiLoading(true);
    try {
      const formDataUpload = new FormData();
      formDataUpload.append('file', file);
      
      const response = await api.post('/ai/extract-invoice', formDataUpload, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });
      
      const data = response.data;
      setFormData(prev => ({
        ...prev,
        client_name: data.client_name || prev.client_name,
        billing_address: data.client_address || prev.billing_address,
        issue_date: data.issue_date || prev.issue_date,
        due_date: data.due_date || prev.due_date,
        discount: data.discount || 0
      }));
      
      if (data.items && data.items.length > 0) {
        setItems(data.items.map((i: any) => ({
          service_name: i.service_name || '',
          description: i.description || '',
          amount: i.amount || 0
        })));
      }
      
    } catch (err) {
      console.error('Failed to parse invoice with AI', err);
      alert('AI Extraction Failed. Please check console for details.');
    } finally {
      setAiLoading(false);
    }
  };

  const handleSubmit = async () => {
    setLoading(true);
    try {
      const currentSubtotal = items.reduce((acc, item) => acc + Number(item.amount), 0);
      const currentGrandTotal = currentSubtotal - Number(formData.discount);
      
      const payload = {
        ...formData,
        shipping_address: formData.billing_address || '',
        subtotal: currentSubtotal,
        grand_total: currentGrandTotal,
        items
      };
      // Note: invoice_number is auto-generated by backend if left empty or 'AUTO'
      
      await api.post('/invoices/', payload);
      navigate('/invoices');
    } catch (err: any) {
      console.error('Failed to create invoice', err);
      const detail = err.response?.data?.detail;
      const errorMsg = typeof detail === 'string' ? detail : 
                       (Array.isArray(detail) ? JSON.stringify(detail) : 'Failed to create invoice');
      alert(`Error: ${errorMsg}`);
    } finally {
      setLoading(false);
    }
  };

  const subtotal = items.reduce((acc, item) => acc + Number(item.amount), 0);
  const grandTotal = subtotal - Number(formData.discount);

  return (
    <div className="create-invoice-page">
      <div className="ai-banner">
        <div className="ai-content">
          <div className="ai-icon-bg"><Sparkles size={24} className="text-orange" /></div>
          <div>
            <h3>Magic Extract with Document AI</h3>
            <p>Upload an existing PDF invoice and let AI fill out this form for you instantly.</p>
          </div>
        </div>
        <div>
          <label className="btn-upload">
            {aiLoading ? 'Processing...' : <><Upload size={18} /> Upload PDF</>}
            <input type="file" accept=".pdf" onChange={handleFileUpload} hidden disabled={aiLoading} />
          </label>
        </div>
      </div>

      <div className="invoice-form-grid">
        <div className="card">
          <h3 className="section-title">Client Details</h3>
          <div className="form-group">
            <label className="label">Client Name</label>
            <input name="client_name" value={formData.client_name} onChange={handleInputChange} className="input-field" placeholder="Acme Corp" />
          </div>
          <div className="form-group">
            <label className="label">Client Email</label>
            <input type="email" name="client_email" value={formData.client_email} onChange={handleInputChange} className="input-field" placeholder="contact@acme.com" />
          </div>
          <div className="form-group">
            <label className="label">Client Phone</label>
            <input type="tel" name="client_phone" value={formData.client_phone} onChange={handleInputChange} className="input-field" placeholder="+1 234 567 8900" />
          </div>
          <div className="form-group">
            <label className="label">Billing Address</label>
            <textarea name="billing_address" value={formData.billing_address} onChange={handleInputChange} className="input-field" rows={2} />
          </div>
          <div className="form-group">
            <label className="label">Client Tax Number (Optional)</label>
            <input name="client_tax_number" value={formData.client_tax_number} onChange={handleInputChange} className="input-field" />
          </div>
        </div>

        <div className="card">
          <h3 className="section-title">Invoice Details</h3>
          <div className="form-group">
            <label className="label">Issue Date</label>
            <input type="date" name="issue_date" value={formData.issue_date} onChange={handleInputChange} className="input-field" />
          </div>
          <div className="form-group">
            <label className="label">Due Date</label>
            <input type="date" name="due_date" value={formData.due_date} onChange={handleInputChange} className="input-field" />
          </div>
        </div>
      </div>

      <div className="card items-section">
        <h3 className="section-title">Service Items</h3>
        <div className="items-table-header">
          <div style={{flex: 2}}>Service Name</div>
          <div style={{flex: 3}}>Description</div>
          <div style={{flex: 1}}>Amount</div>
          <div style={{width: '40px'}}></div>
        </div>
        
        {items.map((item, index) => (
          <div key={index} className="item-row animate-fade-in">
            <div style={{flex: 2}}>
              <input value={item.service_name} onChange={(e) => handleItemChange(index, 'service_name', e.target.value)} className="input-field" placeholder="Web Development" />
            </div>
            <div style={{flex: 3}}>
              <input value={item.description} onChange={(e) => handleItemChange(index, 'description', e.target.value)} className="input-field" placeholder="Frontend React work" />
            </div>
            <div style={{flex: 1}}>
              <input type="number" value={item.amount} onChange={(e) => handleItemChange(index, 'amount', parseFloat(e.target.value))} className="input-field text-right" min="0" step="0.01" />
            </div>
            <div style={{width: '40px', display: 'flex', justifyContent: 'center'}}>
              <button className="icon-btn danger" onClick={() => removeItem(index)}><Trash2 size={18} /></button>
            </div>
          </div>
        ))}
        
        <button className="btn-add-item" onClick={addItem}>
          <Plus size={16} /> Add Item
        </button>

        <div className="totals-section">
          <div className="total-row">
            <span>Subtotal:</span>
            <span>{subtotal.toFixed(2)}</span>
          </div>
          <div className="total-row">
            <span>Discount:</span>
            <input 
              type="number" 
              name="discount" 
              value={formData.discount} 
              onChange={handleInputChange} 
              className="input-field min-w" 
              style={{width: '100px'}} 
            />
          </div>
          <div className="total-row grand-total">
            <span>Grand Total:</span>
            <span>{grandTotal.toFixed(2)}</span>
          </div>
        </div>
      </div>

      <div className="form-actions">
        <button className="btn-primary" onClick={handleSubmit} disabled={loading}>
          <Save size={18} style={{marginRight: '8px', display: 'inline'}} />
          {loading ? 'Saving...' : 'Create Invoice'}
        </button>
      </div>
    </div>
  );
};

export default CreateInvoice;
